# Generated by Django 2.0.13 on 2019-07-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbc', '0003_config'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='config',
            unique_together={('account', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('account', 'name')},
        ),
    ]
